version: "3"
services:
  web:
    build: 'web/'
    env_file: app-env.dev
    entrypoint: "/var/www/scripts/start"
    depends_on:
      - db
    volumes:
      - ./web/instance:/var/www/html
      - ./web/scripts:/var/www/scripts
    ports:
      - 8989:80
  db:
    image: percona/percona-server
    env_file: db-env.dev
    ports:
      - 8906:3306
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/config/custom.cnf:/etc/mysql/conf.d/custom.cnf
      - ./db/config/my.cnf:/etc/mysql/my.cnf
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_evolent
    env_file: phpadmin-env.dev
    ports:
     - 8686:80
    volumes:
     - /sessions
    depends_on:
      - db
