<?php


/**
 * Implements hook_library().
 *
 */

function ur_d7_aws_secret_manager_libraries_info() {
  $libraries['aws-sdk-php'] = array(
    // Only used in administrative UI of Libraries API.
    'name' => 'Aws sdk for connecting to aws',
    'vendor url' => 'https://github.com/aws/aws-sdk-php.git',
    'download url' => 'https://github.com/aws/aws-sdk-php/archive/master.zip',
    // It is important that this URL does not include the actual version to
    // download. Not all libraries provide such a static URL.
    'download file url' => 'https://github.com/aws/aws-sdk-php/archive/master.zip',
    // Optional: Define a custom version detection callback, if required.
    'version' => '3.0.0',
    // Default list of files of the library to load. Important: Only specify
    // third-party files belonging to the library here, not integration files of
    // your module.
    'files' => array(
      // For PHP libraries, specify include files here, still relative to the
      // library path.
      'php' => array(
        'vendor/autoload.php',
      ),
    ),
  );
}


/**
 * Implement hook_menu().
 *
 */

function ur_d7_aws_secret_manager_menu() {
  $items = array();

  $items['admin/aws/configs'] = array(
    'title' => 'AWS configs',
    'description' => 'Configure AWS secret crowdtangle',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ur_d7_aws_secret_manager_form'),
    'access callback' => 'user_access',
    'access arguments' => array('administer users'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'includes/ur_d7_aws_secret_manager.form.inc',
  );

   return $items;
}


/**
 * I
 */
