<?php

/**
 * Defining Global Constants
 */

define('CONTACT_V1_TABLE', 'contact_v1');
/**
 * Implementas hook_menu
 */

function evolent_v1_menu() {
  $menu = array();

  $menu['evolent/v1/contact'] = array(
    'title' => 'List  Contacts',
    'page callback' => 'evolent_list_all_contact_v1',
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
    'file' => 'includes/evolent_contact_v1.inc'
  );

  $menu['evolent/v1/contact/add'] = array(
    'title' => 'Add Contact',
    'page callback'=> 'drupal_get_form',
    'page arguments' => array('evolent_add_contact_v1'),
    'access callback' => TRUE,
    'type' => MENU_LOCAL_ACTION,
    'file' => 'includes/evolent_contact_v1.inc'

  );

  $menu['evolent/v1/contact/%contact/edit'] = array(
    'title' => 'Edit Contact',
    'page callback' => 'evolent_edit_contact_v1',
    'page arguments' => array(3),
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
    'file' => 'includes/evolent_contact_v1.inc'

  );

  $menu['evolent/v1/contact/%contact/delete'] = array(
    'title' => 'Delete Contact',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('evolent_delete_contact_v1', 3),
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
    'file' => 'includes/evolent_contact_v1.inc'

  );

  $menu['evolent/v1/contact/%contact/view'] = array(
    'title' => 'View Contact',
    'page callback'=> 'evolent_show_contact_v1',
    'page arguments' => array(3),
    'access callback' => TRUE,
    'type' => MENU_LOCAL_ACTION,
    'file' => 'includes/evolent_contact_v1.inc'

  );

  return $menu;
}


/**
 * Implements hook_permission().
 */

function evolent_v1_permission() {
  $permissions = array();

  $permissions = array(
    'create contact' => array(
      'title' => t('Create Contact'),
      'description' => 'Create a contact',
      ),
    'view contact' => array(
      'title' => t('View A Contact'),
      'description' => 'View a contact',
      ),
    'edit contact' => array(
      'title' => t('Edit a Contact'),
      'description' => 'Edit a contact',
      ),
    'delete contact' => array(
      'title' => t('Delete a Contact'),
      'description' => 'Delete a contact',
      ),
    );

  return $permissions;
}

function contact_load($cid = NULL) {
  module_load_include('inc', 'evolent_v1', 'includes/evolent_contact_v1.utils');
  $contact = contact_load_util(array('cid' => $cid));
  return $contact ? reset($contact) : FALSE;
}

/**
 * Implements hook_theme().
 */

function evolent_v1_theme($existing, $type, $theme, $path) {
  $path = drupal_get_path('module', 'evolent_v1');
  return array(
     'evolent_v1_show_contact' => array(
        'variables' => array('contact' => NULL),
        'template' => 'evolent-v1-contact-view',
        'path' => $path .'/templates'
      )
    );
}

/**
 *  using template preprocess for defining default values
 */
function template_preprocess_evolent_v1_show_contact(&$vars){
  $contact = $vars['contact'];
  $vars['cid'] = $contact->cid;
  $vars['first_name'] = $contact->first_name;
  $vars['last_name'] = $contact->last_name;
  $vars['email'] =  $contact->email;
  $vars['phone_number'] = $contact->phone_number;
  $vars['status'] = $contact->status;
  $author = user_load($contact->uid);
  $vars['author_name'] = $author->name;
}
